const { esClient } = require('../config/elasticsearch');
const { indexMapping, INDEX_NAME } = require('../config/indexMapping');
require('dotenv').config({ path: require('path').join(__dirname, '../../.env') });

const sampleResources = [
    {
        title: 'Introduction to Algorithms',
        authors: ['Thomas H. Cormen', 'Charles E. Leiserson', 'Ronald L. Rivest', 'Clifford Stein'],
        subject: 'Computer Science',
        publisher: 'MIT Press',
        publication_year: 2022,
        resource_type: 'book',
        isbn: '978-0262046305',
        url: 'https://mitpress.mit.edu/books/introduction-algorithms',
        description: 'A comprehensive textbook covering data structures and algorithms including sorting, searching, graph algorithms, and dynamic programming.',
    },
    {
        title: 'Artificial Intelligence: A Modern Approach',
        authors: ['Stuart Russell', 'Peter Norvig'],
        subject: 'Artificial Intelligence',
        publisher: 'Pearson',
        publication_year: 2020,
        resource_type: 'book',
        isbn: '978-0134610993',
        url: 'https://www.pearson.com/ai-modern-approach',
        description: 'The leading textbook on artificial intelligence covering search, knowledge, reasoning, planning, machine learning, and natural language processing.',
    },
    {
        title: 'Deep Learning',
        authors: ['Ian Goodfellow', 'Yoshua Bengio', 'Aaron Courville'],
        subject: 'Machine Learning',
        publisher: 'MIT Press',
        publication_year: 2016,
        resource_type: 'book',
        isbn: '978-0262035613',
        url: 'https://www.deeplearningbook.org/',
        description: 'An in-depth textbook on deep learning covering linear algebra, probability, optimization, convolutional networks, recurrent networks, and generative models.',
    },
    {
        title: 'Design Patterns: Elements of Reusable Object-Oriented Software',
        authors: ['Erich Gamma', 'Richard Helm', 'Ralph Johnson', 'John Vlissides'],
        subject: 'Software Engineering',
        publisher: 'Addison-Wesley',
        publication_year: 1994,
        resource_type: 'book',
        isbn: '978-0201633610',
        url: 'https://www.pearson.com/design-patterns',
        description: 'The classic book on software design patterns including creational, structural, and behavioral patterns for object-oriented programming.',
    },
    {
        title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
        authors: ['Robert C. Martin'],
        subject: 'Software Engineering',
        publisher: 'Prentice Hall',
        publication_year: 2008,
        resource_type: 'book',
        isbn: '978-0132350884',
        url: 'https://www.pearson.com/clean-code',
        description: 'A guide to writing clean, readable, and maintainable code with practical examples and best practices.',
    },
    {
        title: 'Operating System Concepts',
        authors: ['Abraham Silberschatz', 'Peter B. Galvin', 'Greg Gagne'],
        subject: 'Operating Systems',
        publisher: 'Wiley',
        publication_year: 2021,
        resource_type: 'book',
        isbn: '978-1119800361',
        url: 'https://www.wiley.com/os-concepts',
        description: 'Comprehensive coverage of operating system concepts including process management, memory management, file systems, and security.',
    },
    {
        title: 'Computer Networking: A Top-Down Approach',
        authors: ['James Kurose', 'Keith Ross'],
        subject: 'Computer Networks',
        publisher: 'Pearson',
        publication_year: 2021,
        resource_type: 'book',
        isbn: '978-0136681557',
        url: 'https://www.pearson.com/networking-top-down',
        description: 'A top-down approach to computer networking covering application layer, transport layer, network layer, and link layer protocols.',
    },
    {
        title: 'Database System Concepts',
        authors: ['Abraham Silberschatz', 'Henry F. Korth', 'S. Sudarshan'],
        subject: 'Database Systems',
        publisher: 'McGraw Hill',
        publication_year: 2019,
        resource_type: 'book',
        isbn: '978-0078022159',
        url: 'https://www.mcgraw-hill.com/db-concepts',
        description: 'Comprehensive coverage of database concepts including relational model, SQL, normalization, query processing, transaction management, and distributed databases.',
    },
    {
        title: 'The Art of Computer Programming',
        authors: ['Donald E. Knuth'],
        subject: 'Computer Science',
        publisher: 'Addison-Wesley',
        publication_year: 2011,
        resource_type: 'book',
        isbn: '978-0201896831',
        url: 'https://www-cs-faculty.stanford.edu/~knuth/taocp.html',
        description: 'A monumental multi-volume work covering fundamental algorithms and data structures with mathematical analysis.',
    },
    {
        title: 'Structure and Interpretation of Computer Programs',
        authors: ['Harold Abelson', 'Gerald Jay Sussman'],
        subject: 'Computer Science',
        publisher: 'MIT Press',
        publication_year: 1996,
        resource_type: 'book',
        isbn: '978-0262510875',
        url: 'https://mitpress.mit.edu/sites/default/files/sicp/index.html',
        description: 'A foundational text on computer science covering abstraction, recursion, interpreters, and object-oriented programming using Scheme.',
    },
    {
        title: 'Pattern Recognition and Machine Learning',
        authors: ['Christopher M. Bishop'],
        subject: 'Machine Learning',
        publisher: 'Springer',
        publication_year: 2006,
        resource_type: 'book',
        isbn: '978-0387310732',
        url: 'https://www.springer.com/pattern-recognition-ml',
        description: 'An accessible introduction to pattern recognition and machine learning covering probability distributions, classification, regression, and neural networks.',
    },
    {
        title: 'Computer Vision: Algorithms and Applications',
        authors: ['Richard Szeliski'],
        subject: 'Computer Vision',
        publisher: 'Springer',
        publication_year: 2022,
        resource_type: 'book',
        isbn: '978-3030343712',
        url: 'https://szeliski.org/Book/',
        description: 'Comprehensive textbook on computer vision covering image formation, feature detection, segmentation, recognition, and 3D reconstruction.',
    },
    {
        title: 'Natural Language Processing with Python',
        authors: ['Steven Bird', 'Ewan Klein', 'Edward Loper'],
        subject: 'Natural Language Processing',
        publisher: "O'Reilly Media",
        publication_year: 2009,
        resource_type: 'book',
        isbn: '978-0596516499',
        url: 'https://www.nltk.org/book/',
        description: 'A practical introduction to NLP using Python and NLTK covering tokenization, tagging, parsing, and text classification.',
    },
    {
        title: 'Cryptography and Network Security',
        authors: ['William Stallings'],
        subject: 'Cybersecurity',
        publisher: 'Pearson',
        publication_year: 2022,
        resource_type: 'book',
        isbn: '978-0136097044',
        url: 'https://www.pearson.com/crypto-network-security',
        description: 'Covers symmetric and asymmetric cryptography, authentication, digital signatures, network security, and cyber security principles.',
    },
    {
        title: 'Discrete Mathematics and Its Applications',
        authors: ['Kenneth H. Rosen'],
        subject: 'Mathematics',
        publisher: 'McGraw Hill',
        publication_year: 2019,
        resource_type: 'book',
        isbn: '978-1259676512',
        url: 'https://www.mcgraw-hill.com/discrete-math',
        description: 'A thorough introduction to discrete mathematics covering logic, sets, relations, functions, graphs, trees, and combinatorics.',
    },
    {
        title: 'Linear Algebra and Its Applications',
        authors: ['David C. Lay', 'Steven R. Lay', 'Judi J. McDonald'],
        subject: 'Mathematics',
        publisher: 'Pearson',
        publication_year: 2021,
        resource_type: 'book',
        isbn: '978-0135851258',
        url: 'https://www.pearson.com/linear-algebra',
        description: 'A comprehensive textbook covering linear equations, matrix algebra, vector spaces, eigenvalues, and orthogonality.',
    },
    {
        title: 'Probability and Statistics for Engineers and Scientists',
        authors: ['Ronald E. Walpole', 'Raymond H. Myers'],
        subject: 'Statistics',
        publisher: 'Pearson',
        publication_year: 2016,
        resource_type: 'book',
        isbn: '978-0134115856',
        url: 'https://www.pearson.com/prob-stats',
        description: 'A textbook on probability theory and statistics covering distributions, hypothesis testing, regression, and analysis of variance.',
    },
    {
        title: 'Quantum Computing: An Applied Approach',
        authors: ['Jack D. Hidary'],
        subject: 'Quantum Computing',
        publisher: 'Springer',
        publication_year: 2021,
        resource_type: 'book',
        isbn: '978-3030832735',
        url: 'https://www.springer.com/quantum-computing',
        description: 'An introduction to quantum computing covering qubits, quantum gates, quantum algorithms, and practical quantum programming.',
    },
    {
        title: 'Compilers: Principles, Techniques, and Tools',
        authors: ['Alfred V. Aho', 'Monica S. Lam', 'Ravi Sethi', 'Jeffrey D. Ullman'],
        subject: 'Computer Science',
        publisher: 'Pearson',
        publication_year: 2006,
        resource_type: 'book',
        isbn: '978-0321486813',
        url: 'https://www.pearson.com/compilers',
        description: 'The Dragon Book — a classic textbook on compiler design covering lexical analysis, parsing, semantic analysis, code generation, and optimization.',
    },
    {
        title: 'Human-Computer Interaction: An Empirical Research Perspective',
        authors: ['I. Scott MacKenzie'],
        subject: 'Human Computer Interaction',
        publisher: 'Morgan Kaufmann',
        publication_year: 2013,
        resource_type: 'book',
        isbn: '978-0124058651',
        url: 'https://www.elsevier.com/hci-empirical',
        description: 'Covers empirical research methods in HCI, including user studies, experimental design, and usability evaluation.',
    },
    // Journals
    {
        title: 'Attention Is All You Need',
        authors: ['Ashish Vaswani', 'Noam Shazeer', 'Niki Parmar', 'Jakob Uszkoreit'],
        subject: 'Machine Learning',
        publisher: 'NeurIPS',
        publication_year: 2017,
        resource_type: 'journal',
        isbn: '',
        url: 'https://arxiv.org/abs/1706.03762',
        description: 'The seminal paper introducing the Transformer architecture which revolutionized natural language processing and deep learning.',
    },
    {
        title: 'BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding',
        authors: ['Jacob Devlin', 'Ming-Wei Chang', 'Kenton Lee', 'Kristina Toutanova'],
        subject: 'Natural Language Processing',
        publisher: 'ACL',
        publication_year: 2019,
        resource_type: 'journal',
        isbn: '',
        url: 'https://arxiv.org/abs/1810.04805',
        description: 'Introduces BERT, a pre-trained bidirectional transformer model that achieved state-of-the-art results on multiple NLP benchmarks.',
    },
    {
        title: 'ImageNet Classification with Deep Convolutional Neural Networks',
        authors: ['Alex Krizhevsky', 'Ilya Sutskever', 'Geoffrey E. Hinton'],
        subject: 'Computer Vision',
        publisher: 'NeurIPS',
        publication_year: 2012,
        resource_type: 'journal',
        isbn: '',
        url: 'https://papers.nips.cc/paper/4824-imagenet-classification',
        description: 'The AlexNet paper that demonstrated deep convolutional neural networks could dramatically improve image classification performance.',
    },
    {
        title: 'MapReduce: Simplified Data Processing on Large Clusters',
        authors: ['Jeffrey Dean', 'Sanjay Ghemawat'],
        subject: 'Distributed Systems',
        publisher: 'USENIX',
        publication_year: 2004,
        resource_type: 'journal',
        isbn: '',
        url: 'https://research.google/pubs/pub62/',
        description: 'Introduces the MapReduce programming model for processing and generating large data sets in parallel across distributed clusters.',
    },
    {
        title: 'The Google File System',
        authors: ['Sanjay Ghemawat', 'Howard Gobioff', 'Shun-Tak Leung'],
        subject: 'Distributed Systems',
        publisher: 'ACM SOSP',
        publication_year: 2003,
        resource_type: 'journal',
        isbn: '',
        url: 'https://research.google/pubs/pub51/',
        description: 'Describes GFS, a scalable distributed file system designed for large-scale data-intensive applications running on commodity hardware.',
    },
    {
        title: 'A Relational Model of Data for Large Shared Data Banks',
        authors: ['Edgar F. Codd'],
        subject: 'Database Systems',
        publisher: 'Communications of the ACM',
        publication_year: 1970,
        resource_type: 'journal',
        isbn: '',
        url: 'https://dl.acm.org/doi/10.1145/362384.362685',
        description: 'The foundational paper introducing the relational model for database management, which became the basis for SQL and modern RDBMS.',
    },
    {
        title: 'Bitcoin: A Peer-to-Peer Electronic Cash System',
        authors: ['Satoshi Nakamoto'],
        subject: 'Cybersecurity',
        publisher: 'Self-published',
        publication_year: 2008,
        resource_type: 'journal',
        isbn: '',
        url: 'https://bitcoin.org/bitcoin.pdf',
        description: 'The original whitepaper introducing Bitcoin, blockchain technology, and decentralized cryptographic electronic payment systems.',
    },
    {
        title: 'Gradient-Based Learning Applied to Document Recognition',
        authors: ['Yann LeCun', 'Léon Bottou', 'Yoshua Bengio', 'Patrick Haffner'],
        subject: 'Machine Learning',
        publisher: 'IEEE',
        publication_year: 1998,
        resource_type: 'journal',
        isbn: '',
        url: 'https://ieeexplore.ieee.org/document/726791',
        description: 'Introduces convolutional neural networks (LeNet) for handwriting recognition and document analysis.',
    },
    {
        title: 'Generative Adversarial Nets',
        authors: ['Ian Goodfellow', 'Jean Pouget-Abadie', 'Mehdi Mirza', 'Bing Xu'],
        subject: 'Machine Learning',
        publisher: 'NeurIPS',
        publication_year: 2014,
        resource_type: 'journal',
        isbn: '',
        url: 'https://arxiv.org/abs/1406.2661',
        description: 'Proposes generative adversarial networks (GANs), a framework for training generative models using adversarial training.',
    },
    {
        title: 'Playing Atari with Deep Reinforcement Learning',
        authors: ['Volodymyr Mnih', 'Koray Kavukcuoglu', 'David Silver'],
        subject: 'Artificial Intelligence',
        publisher: 'DeepMind',
        publication_year: 2013,
        resource_type: 'journal',
        isbn: '',
        url: 'https://arxiv.org/abs/1312.5602',
        description: 'The DQN paper that demonstrated deep reinforcement learning agents could learn to play Atari games directly from pixel inputs.',
    },
    // Digital Resources
    {
        title: 'MIT OpenCourseWare: Introduction to Computer Science and Programming Using Python',
        authors: ['Ana Bell', 'Eric Grimson', 'John Guttag'],
        subject: 'Computer Science',
        publisher: 'MIT OpenCourseWare',
        publication_year: 2023,
        resource_type: 'digital',
        isbn: '',
        url: 'https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/',
        description: 'A free online course covering Python programming, computational thinking, data structures, and algorithms.',
    },
    {
        title: 'Stanford CS229: Machine Learning Course Notes',
        authors: ['Andrew Ng'],
        subject: 'Machine Learning',
        publisher: 'Stanford University',
        publication_year: 2022,
        resource_type: 'digital',
        isbn: '',
        url: 'https://cs229.stanford.edu/',
        description: 'Lecture notes and materials for Stanford\'s machine learning course covering supervised learning, unsupervised learning, and reinforcement learning.',
    },
    {
        title: 'The Missing Semester of Your CS Education',
        authors: ['Anish Athalye', 'Jon Gjengset', 'Jose Javier Gonzalez Ortiz'],
        subject: 'Computer Science',
        publisher: 'MIT',
        publication_year: 2020,
        resource_type: 'digital',
        isbn: '',
        url: 'https://missing.csail.mit.edu/',
        description: 'Covers practical computing skills often missing from CS curricula: shell scripting, version control, debugging, and security.',
    },
    {
        title: 'Elasticsearch: The Definitive Guide',
        authors: ['Clinton Gormley', 'Zachary Tong'],
        subject: 'Information Retrieval',
        publisher: "O'Reilly Media",
        publication_year: 2015,
        resource_type: 'digital',
        isbn: '978-1449358549',
        url: 'https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html',
        description: 'A comprehensive guide to Elasticsearch covering indexing, search, aggregations, and cluster management for information retrieval.',
    },
    {
        title: 'Think Python: How to Think Like a Computer Scientist',
        authors: ['Allen B. Downey'],
        subject: 'Computer Science',
        publisher: 'Green Tea Press',
        publication_year: 2015,
        resource_type: 'digital',
        isbn: '978-1491939369',
        url: 'https://greenteapress.com/thinkpython2/html/',
        description: 'A free beginner-friendly introduction to programming using Python covering variables, functions, conditionals, loops, and objects.',
    },
    {
        title: 'Pro Git',
        authors: ['Scott Chacon', 'Ben Straub'],
        subject: 'Software Engineering',
        publisher: 'Apress',
        publication_year: 2014,
        resource_type: 'digital',
        isbn: '978-1484200773',
        url: 'https://git-scm.com/book/en/v2',
        description: 'A thorough guide to the Git version control system covering branching, merging, rebasing, and distributed workflows.',
    },
    {
        title: 'Mathematics for Machine Learning',
        authors: ['Marc Peter Deisenroth', 'A. Aldo Faisal', 'Cheng Soon Ong'],
        subject: 'Mathematics',
        publisher: 'Cambridge University Press',
        publication_year: 2020,
        resource_type: 'digital',
        isbn: '978-1108455145',
        url: 'https://mml-book.github.io/',
        description: 'Covers the mathematical foundations of machine learning including linear algebra, analytic geometry, probability, and optimization.',
    },
    {
        title: 'Practical Cryptography for Developers',
        authors: ['Svetlin Nakov'],
        subject: 'Cybersecurity',
        publisher: 'Self-published',
        publication_year: 2018,
        resource_type: 'digital',
        isbn: '',
        url: 'https://cryptobook.nakov.com/',
        description: 'A practical guide to modern cryptography for software developers covering hashing, symmetric and asymmetric encryption, and digital signatures.',
    },
    {
        title: 'The Feynman Lectures on Physics',
        authors: ['Richard P. Feynman', 'Robert B. Leighton', 'Matthew Sands'],
        subject: 'Physics',
        publisher: 'Caltech',
        publication_year: 2013,
        resource_type: 'digital',
        isbn: '978-0465023820',
        url: 'https://www.feynmanlectures.caltech.edu/',
        description: 'Classic physics lectures covering mechanics, electromagnetism, and quantum mechanics made available as a free online resource.',
    },
    {
        title: 'Software Architecture Patterns',
        authors: ['Mark Richards'],
        subject: 'Software Engineering',
        publisher: "O'Reilly Media",
        publication_year: 2015,
        resource_type: 'digital',
        isbn: '',
        url: 'https://www.oreilly.com/library/view/software-architecture-patterns/9781491971437/',
        description: 'An overview of common software architecture patterns including layered, event-driven, microservices, and space-based architectures.',
    },
    {
        title: 'Reinforcement Learning: An Introduction',
        authors: ['Richard S. Sutton', 'Andrew G. Barto'],
        subject: 'Machine Learning',
        publisher: 'MIT Press',
        publication_year: 2018,
        resource_type: 'book',
        isbn: '978-0262039246',
        url: 'http://incompleteideas.net/book/the-book-2nd.html',
        description: 'The definitive introductory textbook on reinforcement learning covering MDPs, dynamic programming, Monte Carlo methods, and policy gradient methods.',
    },
    {
        title: 'Computer Architecture: A Quantitative Approach',
        authors: ['John L. Hennessy', 'David A. Patterson'],
        subject: 'Computer Architecture',
        publisher: 'Morgan Kaufmann',
        publication_year: 2019,
        resource_type: 'book',
        isbn: '978-0128119051',
        url: 'https://www.elsevier.com/computer-architecture',
        description: 'Covers computer architecture fundamentals including instruction set design, pipelining, memory hierarchy, parallelism, and warehouse-scale computing.',
    },
    {
        title: 'Distributed Systems: Principles and Paradigms',
        authors: ['Andrew S. Tanenbaum', 'Maarten Van Steen'],
        subject: 'Distributed Systems',
        publisher: 'Pearson',
        publication_year: 2017,
        resource_type: 'book',
        isbn: '978-1543057386',
        url: 'https://www.distributed-systems.net/index.php/books/ds3/',
        description: 'Covers distributed systems principles including communication, naming, replication, fault tolerance, and consistency.',
    },
    {
        title: 'Graph Neural Networks: Foundations, Frontiers, and Applications',
        authors: ['Lingfei Wu', 'Peng Cui', 'Jian Pei', 'Liang Zhao'],
        subject: 'Machine Learning',
        publisher: 'Springer',
        publication_year: 2022,
        resource_type: 'book',
        isbn: '978-9811660535',
        url: 'https://www.springer.com/graph-neural-networks',
        description: 'Comprehensive coverage of graph neural networks including spectral and spatial methods, recurrent GNNs, and applications.',
    },
    {
        title: 'Information Retrieval: Implementing and Evaluating Search Engines',
        authors: ['Stefan Büttcher', 'Charles L. A. Clarke', 'Gordon V. Cormack'],
        subject: 'Information Retrieval',
        publisher: 'MIT Press',
        publication_year: 2010,
        resource_type: 'book',
        isbn: '978-0262026512',
        url: 'https://mitpress.mit.edu/ir-search-engines',
        description: 'Covers information retrieval fundamentals including indexing, query processing, ranking, evaluation, and web search.',
    },
    {
        title: 'An Introduction to Statistical Learning',
        authors: ['Gareth James', 'Daniela Witten', 'Trevor Hastie', 'Robert Tibshirani'],
        subject: 'Statistics',
        publisher: 'Springer',
        publication_year: 2021,
        resource_type: 'digital',
        isbn: '978-1071614174',
        url: 'https://www.statlearning.com/',
        description: 'An accessible overview of statistical learning covering regression, classification, resampling, tree-based methods, SVMs, and deep learning.',
    },
    {
        title: 'Advanced Data Structures',
        authors: ['Peter Brass'],
        subject: 'Computer Science',
        publisher: 'Cambridge University Press',
        publication_year: 2008,
        resource_type: 'book',
        isbn: '978-0521880374',
        url: 'https://www.cambridge.org/advanced-data-structures',
        description: 'In-depth coverage of advanced data structures including balanced search trees, hash tables, priority queues, and computational geometry structures.',
    },
    {
        title: 'The Pragmatic Programmer: Your Journey to Mastery',
        authors: ['David Thomas', 'Andrew Hunt'],
        subject: 'Software Engineering',
        publisher: 'Addison-Wesley',
        publication_year: 2019,
        resource_type: 'book',
        isbn: '978-0135957059',
        url: 'https://pragprog.com/titles/tpp20/',
        description: 'Updated classic covering practical software engineering topics including DRY principle, orthogonality, refactoring, testing, and pragmatic techniques.',
    },
];

async function seed() {
    try {
        console.log('🔌 Connecting to Elasticsearch...');

        // Check connection
        const health = await esClient.cluster.health();
        console.log(`✅ Connected to ES cluster: ${health.cluster_name} (status: ${health.status})`);

        // Delete existing index if it exists
        const indexExists = await esClient.indices.exists({ index: INDEX_NAME });
        if (indexExists) {
            console.log(`🗑️  Deleting existing index '${INDEX_NAME}'...`);
            await esClient.indices.delete({ index: INDEX_NAME });
        }

        // Create index with mappings
        console.log(`📦 Creating index '${INDEX_NAME}' with custom mappings...`);
        await esClient.indices.create({
            index: INDEX_NAME,
            body: indexMapping,
        });

        // Bulk index sample data
        console.log(`📚 Indexing ${sampleResources.length} resources...`);
        const operations = sampleResources.flatMap((doc) => [
            { index: { _index: INDEX_NAME } },
            doc,
        ]);

        const bulkResult = await esClient.bulk({ body: operations, refresh: 'wait_for' });

        if (bulkResult.errors) {
            const errorItems = bulkResult.items.filter((item) => item.index && item.index.error);
            console.error(`❌ ${errorItems.length} documents failed to index:`);
            errorItems.forEach((item) => console.error(item.index.error));
        } else {
            console.log(`✅ Successfully indexed ${sampleResources.length} resources!`);
        }

        // Verify count
        const count = await esClient.count({ index: INDEX_NAME });
        console.log(`📊 Total documents in index: ${count.count}`);
        console.log('\n🎉 Seed complete! You can now start the server.');
    } catch (err) {
        console.error('❌ Seed failed:', err.message);
        process.exit(1);
    }
}

seed();
